name: "Create Pull Request"
description: "Create a pull request on GitHub."
author: "AgentSprint"

inputs:
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository name"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  labels:
    description: "Labels to add to the pull request"
    required: true
  token:
    description: "GitHub token (optional). Omit to use the caller's GITHUB_TOKEN."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: pull request update labels
      id: pull_request_update_labels
      shell: bash
      env:
        AUTH_TOKEN: ${{ inputs.token != '' && inputs.token || github.token }}
      run: |
        set -euo pipefail
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/issues/${{ inputs.pr_number }}/labels \
        -d "{\"labels\":[\"${{ inputs.labels }}\"]}"