name: "Workflow:dispatch"
description: "Dispatch a GitHub Actions workflow (supports cross-repo)."
author: "AgentSprint"

inputs:
  repo_name:
    description: "Repository name (e.g. infra-azure)"
    required: true
  workflow_name:
    description: "Workflow name (e.g. new_infra)"
    required: true
  branch_name:
    description: "Branch name (e.g. main)"
    required: true
  inputs:
    description: "Comment body (Markdown supported)"
    required: true
  token:
    description: "GitHub token (optional). Omit to use the caller's GITHUB_TOKEN."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: workflows dispatches
      shell: bash
      env:
        AUTH_TOKEN: ${{ inputs.token != '' && inputs.token || github.token }}
      run: |
        set -euo pipefail
        curl -sS -f -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/AgentSprint/${{ inputs.repo_name }}/actions/workflows/${{ inputs.workflow_name }}.yml/dispatches \
        -d "{\"ref\":\"${{ inputs.branch_name }}\",\"inputs\":${{ inputs.inputs }}}"
