name: "Workflow:dispatch"
description: "Dispatch a GitHub Actions workflow (supports cross-repo)."
author: "AgentSprint"

inputs:
  owner:
    description: "Repo owner/org (defaults to caller)"
    required: false
    default: ""
  repo:
    description: "Repository name (e.g. infra-azure)"
    required: true
  workflow_file:
    description: "Workflow file (e.g. new_infra.yml or .github/workflows/new_infra.yml)"
    required: true
  ref:
    description: "Git ref/branch (e.g. main)"
    required: true
  payload_json:
    description: "JSON object for workflow_dispatch inputs"
    required: true
  token:
    description: "GitHub token; if empty uses caller's GITHUB_TOKEN"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Dispatch workflow via API
      shell: bash
      env:
        IN_OWNER: ${{ inputs.owner }}
        IN_REPO: ${{ inputs.repo }}
        IN_WORKFLOW: ${{ inputs.workflow_file }}
        IN_REF: ${{ inputs.ref }}
        IN_PAYLOAD: ${{ inputs.payload_json }}
        IN_TOKEN: ${{ inputs.token }}
        CALLER_OWNER: ${{ github.repository_owner }}
        CALLER_TOKEN: ${{ github.token }}
        AUTH_TOKEN: ${{ inputs.token != '' && inputs.token || github.token }}
      run: |
        set -euo pipefail
        curl -sS -f -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${AUTH_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ env.IN_OWNER }}/${{ env.IN_REPO }}/actions/workflows/${{ env.IN_WORKFLOW }}.yml/dispatches \
        -d "{\"ref\":\"${{ env.IN_REF }}\",\"inputs\":${{ env.IN_PAYLOAD }}}"
