name: "Workflow:dispatch"
description: "Dispatch a GitHub Actions workflow (supports cross-repo)."
author: "AgentSprint"

inputs:
  owner:
    description: "Repo owner/org (defaults to caller)"
    required: false
    default: ""
  repo:
    description: "Repository name (e.g. infra-azure)"
    required: true
  workflow_file:
    description: "Workflow file (e.g. new_infra.yml or .github/workflows/new_infra.yml)"
    required: true
  ref:
    description: "Git ref/branch (e.g. main)"
    required: true
  payload_json:
    description: "JSON object for workflow_dispatch inputs"
    required: true
  token:
    description: "GitHub token; if empty uses caller's GITHUB_TOKEN"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Dispatch workflow via API
      shell: bash
      env:
        IN_OWNER: ${{ inputs.owner }}
        IN_REPO: ${{ inputs.repo }}
        IN_WORKFLOW: ${{ inputs.workflow_file }}
        IN_REF: ${{ inputs.ref }}
        IN_PAYLOAD: ${{ inputs.payload_json }}
        IN_TOKEN: ${{ inputs.token }}
        CALLER_OWNER: ${{ github.repository_owner }}
        CALLER_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        OWNER="${IN_OWNER:-$CALLER_OWNER}"
        REPO="${IN_REPO}"
        WORKFLOW="${IN_WORKFLOW}"
        REF="${IN_REF}"
        TOKEN="${IN_TOKEN:-$CALLER_TOKEN}"
        PAYLOAD="${IN_PAYLOAD}"

        # quick JSON sanity check (uses Node, available on runners)
        node -e "JSON.parse(process.env.PAYLOAD)" || { echo "payload_json is not valid JSON"; exit 1; }

        URL="https://api.github.com/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/dispatches"

        # Use --fail-with-body if available so you can see API errors
        if curl --help all 2>/dev/null | grep -q -- '--fail-with-body'; then
          curl --fail-with-body -sS -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${URL}" \
            -d "{\"ref\":\"${REF}\",\"inputs\":${PAYLOAD}}"
        else
          resp="$(curl -sS -L -w '\n%{http_code}' \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${URL}" \
            -d "{\"ref\":\"${REF}\",\"inputs\":${PAYLOAD}}")"
          code="${resp##*$'\n'}"; body="${resp%$'\n'$code}"
          echo "$body"
          test "$code" -lt 400
        fi
