name: "close on Issue"
description: "Close a GitHub issue (supports cross-repo)."
author: "AgentSprint"

inputs:
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository name"
    required: true
  branch_name:
    description: "Branch name to delete"
    required: true
  token:
    description: "GitHub token (optional). Omit to use the caller's GITHUB_TOKEN."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Post comment
      shell: bash
      env:
        AUTH_TOKEN: ${{ inputs.token != '' && inputs.token || github.token }}
      run: |
        set -euo pipefail
        curl -sS -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${AUTH_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/git/refs/heads/${{ inputs.branch_name }}